version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
        update-types:
          - minor
          - patch
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - "@nestjs/*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: typescript
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        update-types:
          - minor
          - patch
